audio:
  chunk_size: 264600
  dim_f: 2048
  dim_t: 259
  hop_length: 1024
  n_fft: 6144
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  target_instrument: vocals
  sources:
    - vocals
    - drums
    - bass
    - other
  audio_channels: 2
  n_fft: 6144
  hop_size: 1024
  win_size: 6144
  freq_dim: 2048
  n_bands: 4
  G: 56
  n_enc: 3
  n_dec: 1
  n_split_enc: 3
  n_split_dec: 1
  n_rope: 5
  bn_factor: 4
  normalized: true
  transformer_params:
    heads: 4
    dim_head: 32
    ff_mult: 2
    attn_dropout: 0.0
    proj_dropout: 0.0
    ff_dropout: 0.0
    flash_attn: true

training:
  batch_size: 4
  gradient_accumulation_steps: 1
  instruments:
    - vocals
    - drums
    - bass
    - other
  target_instrument: vocals
  lr: 5.0e-04
  num_epochs: 1000
  num_steps: 1000
  optimizer: adamw
  use_amp: true
  ema_momentum: 0.999
  patience: 2
  reduce_factor: 0.95
  weight_decay: 0.001
  pre_valid: false

augmentations:
  enable: true
  loudness: true
  loudness_min: 0.5
  loudness_max: 1.5

inference:
  batch_size: 1
  dim_t: 259
  num_overlap: 4
